### ISSUE TITLE
 In silico mutagenesis 

### ISSUE THREAD

**Issue by onionpork** [chenkenbio/SpliceBERT#2]
Hi there,

Thank you so much for this awesome paper!
I am wondering how do you implement  in silico mutagenesis analysis?
Is there any materials that I can look into?

Thank you so much!

**Comment by chenkenbio** [comment]
Hello, thanks for reaching out. I am not sure which part you are referring to. Generally, we computed the difference in predictions for reference sequences (extracted from reference genome) and mutant sequences (with manually-introduced variants) to assess the impact of the variants. We also provided demo scripts of in silico mutagenesis analysis: [insilico_mutagenesis_data.py](https://github.com/biomed-AI/SpliceBERT/blob/main/examples/scripts/insilico_mutagenesis_data.py) (dataset) and [insilico_mutagenesis_in_transcripts.py](https://github.com/biomed-AI/SpliceBERT/blob/main/examples/scripts/insilico_mutagenesis_in_transcripts.py) (main script). This method has been used in many studies and was first introduced in [DeepSEA](https://doi.org/10.1038/nmeth.3547) to the best of my knowledge.
